version: '2'

services:
  main:
    build:
      context: ../
      dockerfile: MainPage/Dockerfile
    ports:
      - "45000:6000"
      
  calculator:
    build:
      context: ../Calculator
      dockerfile: Dockerfile
    ports:
      - "46000:6000"
